version: "2"

services:
  mysql:
    image: mysql:8.3.0
    container_name: mysql
    volumes:
      - /my/own/datadir:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
    ports:
      - ${DB_PORT}:3306