name: deploy
run-name: deploy job
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env: 
      DB_USERNAME: ${{ secrets.DB_USERNAME }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_DATABASE: ${{ secrets.DB_DATABASE }}
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_DIALECT: ${{ secrets.DB_DIALECT }}
      DB_PORT: ${{ secrets.DB_PORT }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install
      
      - name: Install Railway
        run: npm i -g @railway/cli

      - name: Run database migrations
        run: npm run migration:run

      - name: Deploy
        uses: bervProject/railway-deploy@main
        with:
          railway_token: ${{ secrets.RAILWAY_TOKEN }}
          service: ${{ secrets.RAILWAY_PROJECT_ID }}
          detach: true